### ISSUE TITLE
Change the default world and record the flying 

### ISSUE THREAD

**Issue by Leprechault** [ARK-Electronics/ROS2_PX4_Offboard_Example#15]
Please, I'd like to know what modification I need to make for changing the world in the gazebo and how I can record the flying using the drone RGB camera?

**Comment by dakejahl** [comment]
Please see the PX4 docs
https://docs.px4.io/main/en/sim_gazebo_gz/gazebo_models.html#example-running-one-host-with-multiple-terminals
```
python3 Tools/simulation/gz/simulation-gazebo --lawn
```
```
PX4_GZ_STANDALONE=1 PX4_SYS_AUTOSTART=4001 PX4_SIM_MODEL=gz_x500 PX4_GZ_WORLD=lawn ./build/px4_sitl_default/bin/px4
```
You can get the video from for example the above model using gz_ros_bridge
https://github.com/gazebosim/ros_gz
```
ros2 run ros_gz_bridge parameter_bridge /camera@sensor_msgs/msg/Image@gz.msgs.Image
```

**Comment by Leprechault** [comment]
Thanks @dakejahl !!

**Comment by dakejahl** [comment]
You're welcome!
