### ISSUE TITLE
ekf2 missing data

### ISSUE THREAD

**Issue by Selimooz** [ARK-Electronics/ROS2_PX4_Offboard_Example#19]
![Screenshot from 2024-10-10 11-34-31](https://github.com/user-attachments/assets/be1b0684-f942-4893-b25c-1f9d8fbede46)
When I run the example using the command ros2 launch px4_offboard offboard_velocity_control.launch.py, I get the error shown in the screenshot. Has anyone else encountered a similar issue?

**Comment by edouardrolland** [comment]
I have exactly the same issue after installing from the official PX4 tutorial. I have just tried this one, and I get the same error...
If someone has an idea on how we can fix this it would be amazing!

**Comment by edouardrolland** [comment]
Hi, I've got pb with my installation (ros2-humble, Gazebo-garden, PX4-1.14) for some days.
I supposed an update in Gazebo, but the PX4 test has the same pb.
ros and Gazebo comes from Ubuntu repo (22.04), PX4 from github repo, up-to-date with branch release/1.14
I rebuild everything and make px4_sitl gz_x500 gives
[...]
INFO  [gz_bridge] world: default, model name: x500_0, simulation model: x500
Unknown message type [8].
Unknown message type [8].
Unknown message type [9].
Unknown message type [9].
[...]
WARN  [health_and_arming_checks] Preflight Fail: ekf2 missing data

everything else looks good.
Can someone tell me which part is wrong ?

=======================
I found the problem, I tried to use gazebo-harmonic, and cleaning was not done well (I suppose message definition was dedicated to harmonic).
... hours of search and found right after I asked for help !

**Comment by dakejahl** [comment]
@edouardrolland so a clean build of `px4_sitl` solved the issue?

**Comment by edouardrolland** [comment]
I found a solution this afternoon, I wilk give you more details tomorrow! You can tag me if I forget :)

**Comment by edouardrolland** [comment]
I was able to fix the problem by switching branches in the PX4 GitHub repo. Kudos to @kasperg3 for finding this! I ran the following command and successfully got the simulator to run properly:

```
cd PX4-Autopilot/
git checkout release/1.15
git submodule update --init --recursive
```
Let me know if it helps!

Edouard.

**Comment by Selimooz** [comment]
It's working now. Thanks
