### ISSUE TITLE
PX4 setup script not called during first install

### ISSUE THREAD

**Issue by beniaminopozzan** [ARK-Electronics/ROS2_PX4_Offboard_Example#5]
[Tools/setup/ubuntu.sh](https://github.com/PX4/PX4-Autopilot/blob/main/Tools/setup/ubuntu.sh) is not called after cloning the PX4 repo

https://github.com/ARK-Electronics/ROS2_PX4_Offboard_Example/blob/e7c75a9148a91957705f318ae57c9f2ad08fb237/README.md?plain=1#L23-L27

This, among other things, prevent Gazebo Garden from being installed.

**Comment by bradenwagstaff** [comment]
That is an issue. I'm not sure how I missed that. I'll fix it

**Comment by bradenwagstaff** [comment]
You said "among other things". Are there other issues I'm not seeing?

**Comment by beniaminopozzan** [comment]
Well, as you are not running the setup script, the whole PX4 toolchain is not installed. At the same time, most of it is installed when you install ROS (i.e. the compiler for SITL). But, for example, NuttX will not be installed.
That is what I meant with "among other things".

**Comment by bradenwagstaff** [comment]
I see. Thanks for the contribution I appreciate it
