### ISSUE TITLE
colcon build command executed in wrong directory

### ISSUE THREAD

**Issue by nikhilsnayak** [ARK-Electronics/ROS2_PX4_Offboard_Example#7]
According to the official docs of ROS2, the **colcon build** command must be run in the root directory of the workspace not src in this case **colcon build** must be run in ~/ros2_px4_offboard_example_ws/ directory not ~/ros2_px4_offboard_example_ws/src

**Comment by nikhilsnayak** [comment]
I can submit a PR correcting the mistake if resolving this issue is useful

**Comment by bradenwagstaff** [comment]
Thank you for catching that. Go ahead and correct and submit a PR
