### ISSUE TITLE
Attribute Error VehicleStatus.ARMING_STATE_MAX

### ISSUE THREAD

**Issue by rakmo97** [ARK-Electronics/ROS2_PX4_Offboard_Example#9]
Hello,

I'm having an issue running this. I get to the `ros2 launch px4_offboard offboard_velocity_control.launch.py` command, and everything launches, but the teleop window seems to be disconnected from the simulation. I see in the main terminal this error:

```
[velocity_control-4] AttributeError: type object 'VehicleStatus' has no attribute 'ARMING_STATE_MAX'. Did you mean: 'ARMING_STATE_ARMED'?
```

I checked the file `~/ros2_px4_offboard_example_ws/src/px4_msgs/msg/VehivleStatus.msg`, and indeed there is nothing named ARMING_STATE_MAX defined in it. What do you think the fix is for this?

**Comment by rakmo97** [comment]
And actually, a little bit later I get other AttributeErrors of other things not being defined in VehicleStatus, for example `ARMING_STATE_STANDBY`.

**Comment by rakmo97** [comment]
I'm seeing in this commit for the px4_msgs repo (https://github.com/PX4/px4_msgs/commit/e3d36168a97f0268ab97e626d14858ca644924ef) that they removed several of the ARMING_STATE_* definitions from VehicleStatus.msg.

**Comment by rakmo97** [comment]
Checking out that commit in the px4_msgs made the sim work for me.

**Comment by AlexKlimaj** [comment]
Hi @rakmo97 give this a try.
https://github.com/ARK-Electronics/ROS2_PX4_Offboard_Example/pull/10
